### ISSUE TITLE
Custom pan and zoom per image

### ISSUE THREAD

**Issue by clarkbremer** [changbowen/ZipImageViewer#3]
Hi!  Have you considered adding a way for the user to provide a custom pan and zoom setting for each image?  To highlight the exact detail in each photo?  I have some architectural photos, and I want the slideshow to zoom into a particular detail and then back out.  CB.

**Comment by changbowen** [comment]
Hi,
It could be a nice add-on. However for a specific set of images, wouldn't it make more sense to animate them using a slideshow software? For a casual image browser it feels a bit of an overkill.
If you start using this app as a "slideshow generator", you will find it lacking many more features like video export etc.

**Comment by clarkbremer** [comment]
What I love about your approach is that you don't need to render the movie.  Takes time, space, and I think you lose image quality.  I have a LOT of images.

Ken Burns would zoom in on a particular subject, then pan to another -- not just randomly move around the canvas.

**Comment by changbowen** [comment]
Agree to your thoughts. However it will be a lot of work on the animation as well as UI (to provide an interface for editing parameters for each image). With the current KBE animation, the hard part is to figure out how to allow customizing the pan and zoom without showing any black bars (the background of the slideshow window).
I will look at it when I have time.

**Comment by clarkbremer** [comment]
I actually started coding it myself.  I'll send you a link when I push it
up.

**Comment by changbowen** [comment]
OK great :)

**Comment by clarkbremer** [comment]
https://github.com/clarkbremer/KB30

**Comment by changbowen** [comment]
Since you already have a working sample I'm closing this one.
