### ISSUE TITLE
very nice! but ..

### ISSUE THREAD

**Issue by telanxrays** [changbowen/ZipImageViewer#4]
For easy management, I have a lot of zip packed pictures, this software can use the picture wall to view all images in zip, excellent!
But there are two small problems:
1.Can't get image pixels and use original size preview, or set zoom level in original ratio.
2.Can't remember the size of the last closed window.
Thanks for your work, great software!

**Comment by changbowen** [comment]
Not sure I understood your points (if I understood correctly) because most of the functionalities you mentioned should already be implemented either in the browser or the viewer.
