### ISSUE TITLE
Random Image when playing a slideshow?

### ISSUE THREAD

**Issue by chufferchump** [changbowen/ZipImageViewer#5]
Firstly thank you for this simple to use and very clean looking image viewer, it all works beautifully and I love it. I was also a big fan of your Ken-Burns-Slideshow application too but this is so much slicker in terms of interface. I only really miss one feature.

Would be possible to include a random image mode when playing a slideshow? We had this option in the Ken-Burns-Slideshow application. 

It seems to play the images in alphabetical order only. Even if i select an image in the middle of folder and press play slideshow it still plays from the very first image.

Thanks again for the application.

**Comment by changbowen** [comment]
Glad you like it :)
I agree to your point and will look into it.

**Comment by changbowen** [comment]
added in release [v1.1.7](https://github.com/changbowen/ZipImageViewer/releases/tag/v1.1.7)

**Comment by changbowen** [comment]
FYI the "randomness" is applied separately on two levels: first to containers (folders and archives), then to the contained images.
This way images in different containers are not mixed together during slideshow.

**Comment by chufferchump** [comment]
Thank you so much for the extra feature! I've just tried it and it works like a charm :-)

ZipImageViewer has been my go to image viewer since I discovered it not long ago and it is now my going to be my go to slideshow app. I will definitely be recommending this to other people looking for a slick viewer.

Thanks again for taking the time to update it, I love it.

**Comment by changbowen** [comment]
No thank YOU for helping me improving it :)
